export const GET_ORDERS = 'GET_ORDERS'
export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST'
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'

export const ADMIN_GET_ENTERPRISES_AUTHORIZED = 'ADMIN_GET_ENTERPRISES_AUTHORIZED'
export const ADMIN_GET_ENTERPRISES_AUTHORIZED_REQUEST = 'ADMIN_GET_ENTERPRISES_AUTHORIZED_REQUEST'
export const ADMIN_GET_ENTERPRISES_AUTHORIZED_FAILURE = 'ADMIN_GET_ENTERPRISES_AUTHORIZED_FAILURE'
export const ADMIN_GET_ENTERPRISES_AUTHORIZED_SUCCESS = 'ADMIN_GET_ENTERPRISES_AUTHORIZED_SUCCESS'

export const ADMIN_GET_ENTERPRISES_IN_PROCESS = 'ADMIN_GET_ENTERPRISES_IN_PROCESS'
export const ADMIN_GET_ENTERPRISES_IN_PROCESS_REQUEST = 'ADMIN_GET_ENTERPRISES_IN_PROCESS_REQUEST'
export const ADMIN_GET_ENTERPRISES_IN_PROCESS_FAILURE = 'ADMIN_GET_ENTERPRISES_IN_PROCESS_FAILURE'
export const ADMIN_GET_ENTERPRISES_IN_PROCESS_SUCCESS = 'ADMIN_GET_ENTERPRISES_IN_PROCESS_SUCCESS'

export const ADMIN_GET_ATTACHMENT_IMAGE = 'ADMIN_GET_ATTACHMENT_IMAGE'
export const ADMIN_GET_ATTACHMENT_IMAGE_REQUEST = 'ADMIN_GET_ATTACHMENT_IMAGE_REQUEST'
export const ADMIN_GET_ATTACHMENT_IMAGE_FAILURE = 'ADMIN_GET_ATTACHMENT_IMAGE_FAILURE'
export const ADMIN_GET_ATTACHMENT_IMAGE_SUCCESS = 'ADMIN_GET_ATTACHMENT_IMAGE_SUCCESS'

export const ADMIN_GET_ENTERPRISE_ADMIN = 'ADMIN_GET_ENTERPRISE_ADMIN'
export const ADMIN_GET_ENTERPRISE_ADMIN_REQUEST = 'ADMIN_GET_ENTERPRISE_ADMIN_REQUEST'
export const ADMIN_GET_ENTERPRISE_ADMIN_FAILURE = 'ADMIN_GET_ENTERPRISE_ADMIN_FAILURE'
export const ADMIN_GET_ENTERPRISE_ADMIN_SUCCESS = 'ADMIN_GET_ENTERPRISE_ADMIN_SUCCESS'

export const ADMIN_GET_ENTERPRISE = 'ADMIN_GET_ENTERPRISE'
export const ADMIN_GET_ENTERPRISE_REQUEST = 'ADMIN_GET_ENTERPRISE_REQUEST'
export const ADMIN_GET_ENTERPRISE_FAILURE = 'ADMIN_GET_ENTERPRISE_FAILURE'
export const ADMIN_GET_ENTERPRISE_SUCCESS = 'ADMIN_GET_ENTERPRISE_SUCCESS'

export const MANAGE_ENTERPRISE_STATUS = 'MANAGE_USER_STATUS'
export const MANAGE_ENTERPRISE_STATUS_FAILURE = 'MANAGE_USER_STATUS_FAILURE'

export const OPERATOR_ADMIN_AUDIT_PAYMENT = 'OPERATOR_ADMIN_AUDIT_PAYMENT'
export const OPERATOR_ADMIN_AUDIT_PAYMENT_REQUEST = 'OPERATOR_ADMIN_AUDIT_PAYMENT_REQUEST'
export const OPERATOR_ADMIN_AUDIT_PAYMENT_FAILURE = 'OPERATOR_ADMIN_AUDIT_PAYMENT_FAILURE'
export const OPERATOR_ADMIN_AUDIT_PAYMENT_SUCCESS = 'OPERATOR_ADMIN_AUDIT_PAYMENT_SUCCESS'

export const ADMIN_LOGIN_USER = 'ADMIN_LOGIN_USER'
export const ADMIN_LOGIN_USER_FAILURE = 'ADMIN_LOGIN_USER_FAILURE'
export const ADMIN_LOGIN_USER_SUCCESS = 'ADMIN_LOGIN_USER_SUCCESS'

export const ADMIN_GET_USER_BY_ID_SUCCESS = 'ADMIN_GET_USER_BY_ID_SUCCESS'

export const ADMIN_GET_VALID_ENTERPRISES = 'ADMIN_GET_VALID_ENTERPRISES'
export const ADMIN_GET_VALID_ENTERPRISES_SUCCESS = 'ADMIN_GET_VALID_ENTERPRISES_SUCCESS'


export const REFRESH_CAPTCHA = 'REFRESH_CAPTCHA'

export const UPDATE_ORDER = 'UPDATE_ORDER'

export const ADMIN_GET_FUNDS_INFO = 'ADMIN_GET_FUNDS_INFO'
export const ADMIN_GET_FUNDS_INFO_REQUEST = 'ADMIN_GET_FUNDS_INFO_REQUEST'
export const ADMIN_GET_FUNDS_INFO_FAILURE = 'ADMIN_GET_FUNDS_INFO_FAILURE'
export const ADMIN_GET_FUNDS_INFO_SUCCESS = 'ADMIN_GET_FUNDS_INFO_SUCCESS'

export const ADMIN_GET_PLATFORM_OPERATIONS = 'ADMIN_GET_PLATFORM_OPERATIONS'
export const ADMIN_GET_PLATFORM_OPERATIONS_SUCCESS = 'ADMIN_GET_PLATFORM_OPERATIONS_SUCCESS'
export const ADMIN_GET_PLATFORM_OPERATIONS_REQUEST = 'ADMIN_GET_PLATFORM_OPERATIONS_REQUEST'
export const ADMIN_GET_PLATFORM_OPERATIONS_FAILURE = 'ADMIN_GET_PLATFORM_OPERATIONS_FAILURE'

export const ADMIN_GET_ORDER_OPERATIONS = 'ADMIN_GET_ORDER_OPERATIONS'
export const ADMIN_GET_ORDER_OPERATIONS_SUCCESS = 'ADMIN_GET_ORDER_OPERATIONS_SUCCESS'
export const ADMIN_GET_ORDER_OPERATIONS_REQUEST = 'ADMIN_GET_ORDER_OPERATIONS_REQUEST'
export const ADMIN_GET_ORDER_OPERATIONS_FAILURE = 'ADMIN_GET_ORDER_OPERATIONS_FAILURE'

export const GET_SCF_ORDERS = 'GET_SCF_ORDERS'
export const GET_SCF_ORDERS_REQUEST = 'GET_SCF_ORDERS_REQUEST'
export const GET_SCF_ORDERS_FAILURE = 'GET_SCF_ORDERS_FAILURE'
export const GET_SCF_ORDERS_SUCCESS = 'GET_SCF_ORDERS_SUCCESS'

export const OPERATOR_ADMIN_GET_ORDER_BILLS = 'OPERATOR_ADMIN_GET_ORDER_BILLS'
export const OPERATOR_ADMIN_GET_ORDER_BILLS_SUCCESS = 'OPERATOR_ADMIN_GET_ORDER_BILLS_SUCCESS'
export const OPERATOR_ADMIN_GET_ORDER_BILLS_REQUEST = 'OPERATOR_ADMIN_GET_ORDER_BILLS_REQUEST'
export const OPERATOR_ADMIN_GET_ORDER_BILLS_FAILURE = 'OPERATOR_ADMIN_GET_ORDER_BILLS_FAILURE'

export const OPERATOR_ADMIN_GET_ORDER_BILL = 'OPERATOR_ADMIN_GET_ORDER_BILL'
export const OPERATOR_ADMIN_GET_ORDER_BILL_SUCCESS = 'OPERATOR_ADMIN_GET_ORDER_BILL_SUCCESS'
export const OPERATOR_ADMIN_GET_ORDER_BILL_REQUEST = 'OPERATOR_ADMIN_GET_ORDER_BILL_REQUEST'
export const OPERATOR_ADMIN_GET_ORDER_BILL_FAILURE = 'OPERATOR_ADMIN_GET_ORDER_BILL_FAILURE'

export const OPERATOR_ADMIN_ORDER_BILL_IMPORT = 'OPERATOR_ADMIN_ORDER_BILL_IMPORT'
export const OPERATOR_ADMIN_ORDER_BILL_EXPORT = 'OPERATOR_ADMIN_ORDER_BILL_EXPORT'

export const ADMIN_SET_ENTERPRISE_TABS_KEY = 'ADMIN_SET_ENTERPRISE_TABS_KEY'
