CREATE TABLE `wms_order_type` (
  `id` int(11) NOT NULL,
  `name` varchar(36) NOT NULL,
  `description` varchar(100) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` varchar(36) NOT NULL,
  `updated_by` varchar(36) NOT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  `version` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `wms_order` (
  `id` varchar(36) NOT NULL,
  `user_id` varchar(36) NOT NULL,
  `user_role` varchar(36) NOT NULL,
  `enterprise_id` varchar(36) DEFAULT NULL,
  `status` int(11) NOT NULL,
  `refund_status` tinyint(1) DEFAULT NULL,
  `vendor` varchar(36) NOT NULL DEFAULT 'none',
  `cancel_reason` int(11) DEFAULT NULL,
  `type` int(11) NOT NULL DEFAULT '0',
  `subscription_id` varchar(36) NOT NULL,
  `contact` text NOT NULL,
  `charging_rules` text,
  `currency` varchar(10) DEFAULT 'CNY',
  `effective_from` datetime DEFAULT NULL,
  `effective_to` datetime DEFAULT NULL,
  `approved_price` decimal(10,0) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `created_by` varchar(36) NOT NULL,
  `updated_by` varchar(36) NOT NULL,
  `deleted` tinyint(1) NOT NULL DEFAULT '0',
  `version` int(11) NOT NULL,
  `service_intro` varchar(5000) DEFAULT NULL,
  `max_price` int(11) DEFAULT NULL,
  `min_price` int(11) DEFAULT NULL,
  `enterprise_short_name` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_wms_order_order_status` (`status`),
  KEY `fk_wms_order_wms_order_type` (`type`),
  KEY `wms_order$user_id` (`user_id`),
  KEY `wms_order$enterprise_id` (`enterprise_id`),
  KEY `wms_order$created_at` (`created_at`),
  KEY `wms_order$deleted` (`deleted`),
  KEY `fk_wms_cancel_reason` (`cancel_reason`),
  CONSTRAINT `fk_wms_cancel_reason` FOREIGN KEY (`cancel_reason`) REFERENCES `cancel_reason` (`id`),
  CONSTRAINT `fk_wms_order_order_status` FOREIGN KEY (`status`) REFERENCES `order_status` (`id`),
  CONSTRAINT `fk_wms_order_wms_order_type` FOREIGN KEY (`type`) REFERENCES `wms_order_type` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;