export const ADMIN_GET_ENTERPRISE_HISTORIES = 'ADMIN_GET_ENTERPRISE_HISTORIES'
export const ADMIN_GET_ENTERPRISE_HISTORIES_SUCCESS = 'ADMIN_GET_ENTERPRISE_HISTORIES_SUCCESS'
export const ADMIN_GET_ENTERPRISE_HISTORIES_FAILURE = 'ADMIN_GET_ENTERPRISE_HISTORIES_FAILURE'

export const ADMIN_GET_ADMIN = 'ADMIN_GET_ADMIN'
export const ADMIN_GET_ADMIN_SUCCESS = 'ADMIN_GET_ADMIN_SUCCESS'
