export const GET_ENTERPRISE_INFO = 'GET_ENTERPRISE_INFO'
export const GET_ENTERPRISE_INFO_REQUEST = 'GET_ENTERPRISE_INFO_REQUEST'
export const GET_ENTERPRISE_INFO_FAIL = 'GET_ENTERPRISE_INFO_FAIL'
export const GET_ENTERPRISE_INFO_SUCCESS = 'GET_ENTERPRISE_INFO_SUCCESS'

export const GET_ATTACHMENT_IMAGE = 'GET_ATTACHMENT_IMAGE'
export const GET_ATTACHMENT_IMAGE_REQUEST = 'GET_ATTACHMENT_IMAGE_REQUEST'
export const GET_ATTACHMENT_IMAGE_FAIL = 'GET_ATTACHMENT_IMAGE_FAIL'
export const GET_ATTACHMENT_IMAGE_SUCCESS = 'GET_ATTACHMENT_IMAGE_SUCCESS'

export const GET_ENTERPRISE_HISTORIES = 'GET_ENTERPRISE_HISTORIES'
export const GET_ENTERPRISE_HISTORIES_SUCCESS = 'GET_ENTERPRISE_HISTORIES_SUCCESS'

export const CLEAR_ENTERPRISE_INFO = 'CLEAR_ENTERPRISE_INFO'
