export const GET_PORT_OPTIONS = 'GET_PORT_OPTIONS'
export const GET_PORT_OPTIONS_SUCCESS = 'GET_PORT_OPTIONS_SUCCESS'

export const GET_SUPERVISION_OPTIONS = 'GET_SUPERVISION_OPTIONS'
export const GET_SUPERVISION_OPTIONS_SUCCESS = 'GET_SUPERVISION_OPTIONS_SUCCESS'

export const GET_TRANSPORT_OPTIONS = 'GET_TRANSPORT_OPTIONS'
export const GET_TRANSPORT_OPTIONS_SUCCESS = 'GET_TRANSPORT_OPTIONS_SUCCESS'
export const CLEAR_PRODUCT_LIST = 'CLEAR_PRODUCT_LIST'
