export const GET_ENTERPRISE_USER_LIST = 'GET_ENTERPRISE_USER_LIST'
export const GET_ENTERPRISE_USER_LIST_SUCCESS = 'GET_ENTERPRISE_USER_LIST_SUCCESS'
export const MANAGE_USER_STATUS = 'MANAGE_USER_STATUS'
export const MANAGE_USER_STATUS_FAIL = 'MANAGE_USER_STATUS_FAIL'