export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const GET_USER_BY_ID = 'GET_USER_BY_ID'
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO'
export const SYNC_USER_INFO = 'SYNC_USER_INFO'

export const SET_USER_ENTERPRISE_ID = 'SET_USER_ENTERPRISE_ID'

export const LOGOUT_USER = 'LOGOUT_USER'

export const REFRESH_CAPTCHA = 'REFRESH_CAPTCHA'

export const SHOW_SESSION_EXPIRED_MASK = 'SHOW_SESSION_EXPIRED_MASK'