pipeline {
    agent {
        label 'java'
    }
    stages {
        stage('Build') {
            steps {
                sh "./gradlew clean compileJava compileTestJava --info"
            }
        }
        stage('Publish') {
            steps {
                sh "./gradlew bootRepackage -Prelease --info"
                sh "sudo ./scripts/publish.sh ${env.JOB_BASE_NAME} ${env.BUILD_ID}"
            }
        }
        stage('Deploy') {
            steps {
                sh "sudo ./scripts/deploy.sh ${env.JOB_BASE_NAME} ${env.BUILD_ID}"
            }
        }
    }
}