export const ADD_PRODUCT = 'ADD_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const ADD_PRODUCTS = 'ADD_PRODUCTS'

export const GET_PRODUCT_NAME_OPTIONS = 'GET_PRODUCT_NAME_OPTIONS'
export const GET_PRODUCT_NAME_OPTIONS_SUCCESS = 'GET_PRODUCT_NAME_OPTIONS_SUCCESS'

export const GET_PRODUCT_PRICE_UNIT_OPTIONS = 'GET_PRODUCT_PRICE_UNIT_OPTIONS'
export const GET_PRODUCT_PRICE_UNIT_OPTIONS_SUCCESS = 'GET_PRODUCT_PRICE_UNIT_OPTIONS_SUCCESS'
export const CLEAR_ACG_ORDER_CREATED_INFO = 'CLEAR_ACG_ORDER_CREATED_INFO'
export const CLEAR_PRODUCT_LIST = 'CLEAR_PRODUCT_LIST'
