export const GET_CONTACTS = 'GET_CONTACTS'
export const GET_CONTACTS_REQUEST = 'GET_CONTACTS_REQUEST'
export const GET_CONTACTS_FAILURE = 'GET_CONTACTS_FAILURE'
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS'

export const SELECT_CONTACT = 'SELECT_CONTACT'
export const SELECT_CONTACT_REQUEST = 'SELECT_CONTACT_REQUEST'
export const SELECT_CONTACT_FAILURE = 'SELECT_CONTACT_FAILURE'
export const SELECT_CONTACT_SUCCESS = 'SELECT_CONTACT_SUCCESS'


export const SELECT_CONTACT_FOR_FIRST = 'SELECT_CONTACT_FOR_FIRST'
export const SELECT_CONTACT_FOR_FIRST_REQUEST = 'SELECT_CONTACT_FOR_FIRST_REQUEST'
export const SELECT_CONTACT_FOR_FIRST_FAILURE = 'SELECT_CONTACT_FOR_FIRST_FAILURE'
export const SELECT_CONTACT_FOR_FIRST_SUCCESS = 'SELECT_CONTACT_FOR_FIRST_SUCCESS'

export const SELECT_CONTACT_SECOND = 'SELECT_CONTACT_SECOND'
export const SELECT_CONTACT_REQUEST_SECOND = 'SELECT_CONTACT_REQUEST_SECOND'
export const SELECT_CONTACT_FAILURE_SECOND = 'SELECT_CONTACT_FAILURE_SECOND'
export const SELECT_CONTACT_SUCCESS_SECOND = 'SELECT_CONTACT_SUCCESS_SECOND'


export const SELECT_CONTACT_FOR_SECOND = 'SELECT_CONTACT_FOR_SECOND'
export const SELECT_CONTACT_FOR_SECOND_REQUEST = 'SELECT_CONTACT_FOR_SECOND_REQUEST'
export const SELECT_CONTACT_FOR_SECOND_FAILURE = 'SELECT_CONTACT_FOR_SECOND_FAILURE'
export const SELECT_CONTACT_FOR_SECOND_SUCCESS = 'SELECT_CONTACT_FOR_SECOND_SUCCESS'

export const CREATE_CONTACTS = 'CREATE_CONTACTS'
export const CREATE_CONTACTS_REQUEST = 'CREATE_CONTACTS_REQUEST'
export const CREATE_CONTACTS_FAILURE = 'CREATE_CONTACTS_FAILURE'
export const CREATE_CONTACTS_SUCCESS = 'CREATE_CONTACTS_SUCCESS'

export const UPDATE_CONTACTS = 'UPDATE_CONTACTS'
export const UPDATE_CONTACTS_REQUEST = 'UPDATE_CONTACTS_REQUEST'
export const UPDATE_CONTACTS_FAILURE = 'UPDATE_CONTACTS_FAILURE'
export const UPDATE_CONTACTS_SUCCESS = 'UPDATE_CONTACTS_SUCCESS'

export const CLEAR_CONTACT = 'CLEAR_CONTACT'
export const CLEAR_CONTACT_SECOND = 'CLEAR_CONTACT_SECOND'

export const DELETE_CONTACTS = 'DELETE_CONTACTS'
export const DELETE_CONTACTS_SUCCESS = 'DELETE_CONTACTS_SUCCESS'
export const DELETE_CONTACTS_FAILURE = 'DELETE_CONTACTS_FAILURE'