export const GET_ENTERPRISE_PAY_METHODS = 'GET_ENTERPRISE_PAY_METHODS';
export const GET_ENTERPRISE_PAY_METHODS_SUCCESS = 'GET_ENTERPRISE_PAY_METHODS_SUCCESS';
export const GET_ENTERPRISE_PAY_METHODS_FAILURE = 'GET_ENTERPRISE_PAY_METHODS_FAILURE';