export const GET_AIRPORTS_INFO = 'GET_AIRPORTS_INFO';
export const GET_AIRPORTS_INFO_SUCCESS = 'GET_AIRPORTS_INFO_SUCCESS';
export const GET_AIRPORTS_INFO_FAILURE = 'GET_AIRPORTS_INFO_FAILURE';
export const GET_AIRPORTS_INFO_REQUEST = 'GET_AIRPORTS_INFO_REQUEST';

export const GET_ACG_ORDER = 'GET_ACG_ORDER'
export const GET_ACG_ORDER_REQUEST = 'GET_ACG_ORDER_REQUEST'
export const GET_ACG_ORDER_FAILURE = 'GET_ACG_ORDER_FAILURE'
export const GET_ACG_ORDER_SUCCESS = 'GET_ACG_ORDER_SUCCESS'

export const GET_ACG_ORDERS = 'GET_ACG_ORDERS'
export const GET_ACG_ORDERS_REQUEST = 'GET_ACG_ORDERS_REQUEST'
export const GET_ACG_ORDERS_FAILURE = 'GET_ACG_ORDERS_FAILURE'
export const GET_ACG_ORDERS_SUCCESS = 'GET_ACG_ORDERS_SUCCESS'


export const SAVE_AIRCARGO_PRODUCT_LIST = 'SAVE_AIRCARGO_PRODUCT_LIST'
export const SAVE_AIRCARGO_PRODUCT_INFO = 'SAVE_AIRCARGO_PRODUCT_INFO'
export const UPDATE_AIRCARGO_PRODUCT = 'UPDATE_AIRCARGO_PRODUCT'
export const DELETE_AIRCARGO_PRODUCT = 'DELETE_AIRCARGO_PRODUCT'
export const CREATE_AIRCARGO_ORDER = 'CREATE_AIRCARGO_ORDER'

export const GET_AIRCARGO_ORDER_PRICE = 'GET_AIRCARGO_ORDER_PRICE'
export const GET_AIRCARGO_ORDER_PRICE_REQUEST = 'GET_AIRCARGO_ORDER_PRICE_REQUEST'
export const GET_AIRCARGO_ORDER_PRICE_SUCCESS = 'GET_AIRCARGO_ORDER_PRICE_SUCCESS'
export const GET_AIRCARGO_ORDER_PRICE_FAILURE = 'GET_AIRCARGO_ORDER_PRICE_FAILURE'

export const GET_ACG_PAYMENT_STATUS = 'GET_ACG_PAYMENT_STATUS'
export const GET_ACG_PAYMENT_STATUS_SUCCESS = 'GET_ACG_PAYMENT_STATUS_SUCCESS'
export const GET_ACG_PAYMENT_STATUS_FAILURE = 'GET_ACG_PAYMENT_STATUS_FAILURE'

export const CHANGE_VALIDATION_STATUS = 'CHANGE_VALIDATION_STATUS'

export const SAVE_ACG_PRODUCT_LIST = 'SAVE_ACG_PRODUCT_LIST'

export const GET_ACG_SUPPORTED_DISTRICTS = 'GET_ACG_SUPPORTED_DISTRICTS'
export const GET_ACG_SUPPORTED_DISTRICTS_SUCCESS = 'GET_ACG_SUPPORTED_DISTRICTS_SUCCESS'
export const GET_ACG_SUPPORTED_DISTRICTS_FAILURE = 'GET_ACG_SUPPORTED_DISTRICTS_FAILURE'

export const CLEAR_ACG_SUPPORTED_DISTRICTS = 'CLEAR_ACG_SUPPORTED_DISTRICTS'

export const CLEAR_ACG_ORDER_CREATED_INFO = 'CLEAR_ACG_ORDER_CREATED_INFO'
