export const WMS_GET_ORDER_TEMPLATE = 'WMS_GET_ORDER_TEMPLATE'
export const WMS_GET_ORDER_TEMPLATE_REQUEST = 'WMS_GET_ORDER_TEMPLATE_REQUEST'
export const WMS_GET_ORDER_TEMPLATE_FAILURE = 'WMS_GET_ORDER_TEMPLATE_FAILURE'
export const WMS_GET_ORDER_TEMPLATE_SUCCESS = 'WMS_GET_ORDER_TEMPLATE_SUCCESS'

export const WMS_CREATE_ORDER = 'WMS_CREATE_ORDER'
export const WMS_CREATE_ORDER_REQUEST = 'WMS_CREATE_ORDER_REQUEST'
export const WMS_CREATE_ORDER_FAILURE = 'WMS_CREATE_ORDER_FAILURE'
export const WMS_CREATE_ORDER_SUCCESS = 'WMS_CREATE_ORDER_SUCCESS'

export const WMS_GET_ORDERS_BY_USER = 'WMS_GET_ORDERS_BY_USER'
export const WMS_GET_ORDERS_BY_USER_REQUEST = 'WMS_GET_ORDERS_BY_USER_REQUEST'
export const WMS_GET_ORDERS_BY_USER_FAILURE = 'WMS_GET_ORDERS_BY_USER_FAILURE'
export const WMS_GET_ORDERS_BY_USER_SUCCESS = 'WMS_GET_ORDERS_BY_USER_SUCCESS'

export const WMS_GET_ORDER = 'WMS_GET_ORDER'
export const WMS_GET_ORDER_REQUEST = 'WMS_GET_ORDER_REQUEST'
export const WMS_GET_ORDER_FAILURE = 'WMS_GET_ORDER_FAILURE'
export const WMS_GET_ORDER_SUCCESS = 'WMS_GET_ORDER_SUCCESS'

export const WMS_CLEAR_ORDER = 'WMS_CLEAR_ORDER'

export const WMS_GET_LANDING_PAGE_ORDER = 'WMS_GET_LANDING_PAGE_ORDER'
export const WMS_GET_LANDING_PAGE_ORDER_SUCCESS = 'WMS_GET_LANDING_PAGE_ORDER_SUCCESS'

export const GET_WMS_PAYMENT_STATUS = 'GET_WMS_PAYMENT_STATUS'