export const SIGNUP_USER = 'SIGNUP_USER'
export const SIGNUP_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE'
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'

export const CLEAR_SIGNUP_DATA = 'CLEAR_SIGNUP_DATA'