spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/mall_micro_service_product?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
  application:
      name: product-client
server:
  port: 7777


management:
  endpoint:
    health:
      enabled: true
#      show-details: always
    info:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/