profiles: test
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/mall_micro_service_product_test?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8260/eureka



management:
  endpoint:
    health:
      enabled: true
#      show-details: always
    info:
      enabled: true